// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project3.Data;

#nullable disable

namespace Project3.Migrations
{
    [DbContext(typeof(Sem3DBContext))]
    partial class Sem3DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project3.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AccountId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("AccountStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AccountStatus");

                    b.Property<string>("AccountType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AccountType");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Address");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Avatar");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FullName");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Password");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Phone");

                    b.HasKey("AccountId");

                    b.ToTable("Account");

                    b.HasData(
                        new
                        {
                            AccountId = 1,
                            AccountStatus = "In force",
                            AccountType = "admin",
                            Address = "Tòa Nhà HTC-250 Hoàng Quốc Việt-Cổ Nhuế-Cầu Giấy-Hà Nội",
                            Avatar = "acc1.jpg",
                            Email = "admin@gmail.com",
                            FullName = "Admin",
                            Password = "123456",
                            Phone = "0123456789"
                        },
                        new
                        {
                            AccountId = 2,
                            AccountStatus = "In force",
                            AccountType = "user",
                            Address = "Hà nam city",
                            Avatar = "acc2.jpg",
                            Email = "user@gmail.com",
                            FullName = "User",
                            Password = "123456",
                            Phone = "0328633121"
                        },
                        new
                        {
                            AccountId = 3,
                            AccountStatus = "Disable",
                            AccountType = "user",
                            Address = "Tòa Nhà HTC-250 Hoàng Quốc Việt-Cổ Nhuế-Cầu Giấy-Hà Nội",
                            Avatar = "acc2.jpg",
                            Email = "user2@gmail.com",
                            FullName = "User2",
                            Password = "123456",
                            Phone = "0987654321"
                        });
                });

            modelBuilder.Entity("Project3.Models.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CartId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("AccountId");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductId");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Quantity");

                    b.Property<double?>("TotalPrice")
                        .HasColumnType("float")
                        .HasColumnName("TotalPrice");

                    b.HasKey("CartId");

                    b.HasIndex("AccountId");

                    b.HasIndex("ProductId");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("Project3.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoryId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CategoryName");

                    b.Property<string>("CategoryType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CategoryType");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Digestive medicine",
                            CategoryType = "Medical"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Headache and pain reliever",
                            CategoryType = "Medical"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Fever and flu medicine",
                            CategoryType = "Medical"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Microscope",
                            CategoryType = "Science"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Blood pressure monitors",
                            CategoryType = "Science"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Cardiac event monitor",
                            CategoryType = "Science"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Pulse oximeter",
                            CategoryType = "Science"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Medical Exam tables",
                            CategoryType = "Science"
                        });
                });

            modelBuilder.Entity("Project3.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CommentId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("AccountId");

                    b.Property<DateTime?>("CommentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CommentDate");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Content");

                    b.Property<int?>("NewsId")
                        .HasColumnType("int")
                        .HasColumnName("NewsId");

                    b.HasKey("CommentId");

                    b.HasIndex("AccountId");

                    b.HasIndex("NewsId");

                    b.ToTable("Comment");

                    b.HasData(
                        new
                        {
                            CommentId = 1,
                            AccountId = 1,
                            CommentDate = new DateTime(2024, 1, 3, 15, 4, 37, 153, DateTimeKind.Local).AddTicks(9535),
                            Content = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati beatae non a porro quia? Cumque suscipit dolor repellendus. Eos suscipit tempore dignissimos omnis veniam magnam error hic labore! Labore, aperiam.",
                            NewsId = 2
                        },
                        new
                        {
                            CommentId = 2,
                            AccountId = 2,
                            CommentDate = new DateTime(2024, 1, 3, 15, 4, 37, 153, DateTimeKind.Local).AddTicks(9539),
                            Content = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati beatae non a porro quia? Cumque suscipit dolor repellendus. Eos suscipit tempore dignissimos omnis veniam magnam error hic labore! Labore, aperiam.",
                            NewsId = 2
                        },
                        new
                        {
                            CommentId = 3,
                            AccountId = 2,
                            CommentDate = new DateTime(2024, 1, 3, 15, 4, 37, 153, DateTimeKind.Local).AddTicks(9540),
                            Content = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati beatae non a porro quia? Cumque suscipit dolor repellendus. Eos suscipit tempore dignissimos omnis veniam magnam error hic labore! Labore, aperiam.",
                            NewsId = 3
                        });
                });

            modelBuilder.Entity("Project3.Models.News", b =>
                {
                    b.Property<int>("NewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NewsId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NewsId"));

                    b.Property<string>("LongContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LongContent");

                    b.Property<DateTime?>("NewsDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("NewsDate");

                    b.Property<string>("NewsImage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NewsImage");

                    b.Property<string>("NewsType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NewsType");

                    b.Property<string>("ShortContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ShortContent");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Title");

                    b.HasKey("NewsId");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            NewsId = 1,
                            LongContent = "Speaking at the conference, Deputy Minister of Health Do Xuan Tuyen said that in recent years, with the attention of the Party and State, traditional medicine has inherited, promoted, and developed, achieving important achievements. important in protecting and caring for peoples health. Directions to prioritize the development of traditional medicine (TCM), combining Traditional Medicine with modern medicine, are clearly shown in the content of the Constitution, Platform of the Party Congress, and Resolution of the Central Executive Committee. Central Committee, Politburo and directives of the Secretariat.\r\nCombining traditional medicine with modern medicine is strictly implemented in all fields, from the system of legal documents such as the Law on Medical Examination and Treatment, the Law on Pharmacy,... the state management system of health to medical examination and treatment system, training programs, scientific research, professional documents guiding the implementation of medical examination and treatment, investing in infrastructure construction, purchasing medical equipment, updating Continuous medical knowledge, improving professional qualifications for medical examination and treatment practitioners.",
                            NewsDate = new DateTime(2024, 1, 3, 15, 4, 37, 153, DateTimeKind.Local).AddTicks(9512),
                            NewsImage = "yte1.jpg",
                            NewsType = "Medical",
                            ShortContent = "On December 11, 2023 in Nghe An, the Ministry of Health organized a conference to discuss medical examination and treatment in the field of Traditional Medicine and Pharmacy with the theme Combining traditional medicine with modern medicine. Deputy Minister of Health Do Xuan Tuyen chaired the conference.",
                            Title = "Conference on treatment work in the field of Traditional Medicine and Pharmacy"
                        },
                        new
                        {
                            NewsId = 2,
                            LongContent = "Specifically, the Ministry of Health proposes to amend Point a, Clause 2, Article 54 of the Pharmacy Law, accordingly, medicinal ingredients used to produce drugs according to drug registration dossiers that already have a certificate of registration for circulation in Vietnam do not have to be processed. registration for circulation to reduce and simplify administrative procedures.\r\nThe draft also proposes to supplement Clause 6, Article 56 of the Pharmacy Law, in which, no further extension of the validity of the circulation registration certificate for drugs and medicinal ingredients that have not been circulated on the market within the validity period has been granted. circulation registration certificate.",
                            NewsDate = new DateTime(2024, 1, 3, 15, 4, 37, 153, DateTimeKind.Local).AddTicks(9523),
                            NewsImage = "yte2.jpg",
                            NewsType = "Medical",
                            ShortContent = "In the draft Law amending and supplementing a number of articles of the Pharmacy Law, the Ministry of Health proposes to amend and supplement regulations on registration and circulation of drugs and medicinal ingredients.",
                            Title = "Propose amendments and supplements to regulations on registration and circulation of drugs and medicinal ingredients"
                        },
                        new
                        {
                            NewsId = 3,
                            LongContent = "Specifically, Circular 08/2023/TT-BYT abolishes all 3 legal documents issued by the Minister of Health, including:\r\nCircular No. 03/2016/TT-BYT dated January 21, 2016 of the Minister of Health regulating pharmaceutical business activities.\r\nCircular No. 31/2019/TT-BYT dated December 5, 2019 of the Minister of Health regulating requirements for fresh milk products used in the School Milk Program.\r\nCircular No. 14/2020/TT-BYT dated July 10, 2020 of the Minister of Health regulating a number of contents in bidding for medical equipment at public medical facilities.",
                            NewsDate = new DateTime(2024, 1, 3, 15, 4, 37, 153, DateTimeKind.Local).AddTicks(9523),
                            NewsImage = "kh3.jpg",
                            NewsType = "Science",
                            ShortContent = "The Ministry of Health has just issued Circular 08/2023/TT-BYT abolishing a number of legal documents issued by the Minister of Health. Including Circular No. 14/2020/TT-BYT dated July 10, 2020 of the Minister of Health regulating a number of contents in bidding for medical equipment at public medical facilities.",
                            Title = "Bidding for medical equipment has been resolved"
                        });
                });

            modelBuilder.Entity("Project3.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderDetailId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<int?>("OrdersId")
                        .HasColumnType("int")
                        .HasColumnName("OrdersId");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductId");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Quantity");

                    b.Property<double?>("TotalPrice")
                        .HasColumnType("float")
                        .HasColumnName("TotalPrice");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrdersId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetail");
                });

            modelBuilder.Entity("Project3.Models.Orders", b =>
                {
                    b.Property<int>("OrdersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrdersId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrdersId"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("AccountId");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Note");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("OrderDate");

                    b.Property<string>("OrderStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OrderStatus");

                    b.Property<string>("ReceiverAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ReceiverAddress");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ReceiverName");

                    b.Property<string>("ReceiverPhone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ReceiverPhone");

                    b.HasKey("OrdersId");

                    b.HasIndex("AccountId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Project3.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<double?>("Price")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("Price");

                    b.Property<string>("ProductImage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ProductImage");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ProductName");

                    b.Property<string>("ProductStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ProductStatus");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Description = "Brand	Culturelle\r\nFlavor Unflavored\r\nPrimary Supplement Type Probiotic\r\nUnit Count  30 Count\r\nItem Form Capsule\r\nItem Weight 4.54 Grams\r\nItem Dimensions LxWxH   1.25 x 3.66 x 5.5 inches\r\nSpecial Ingredients All Natural\r\nDiet Type Gluten Free\r\nProduct Benefits Digestive Health Support, Immune Support",
                            Price = 1000.0,
                            ProductImage = "Culturelle.jpg",
                            ProductName = "Culturelle",
                            ProductStatus = "In stock"
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            Description = "Brand	Gas-X\r\nSpecial Feature	fast_acting\r\nItem Weight	22.68 Grams\r\nItem Dimensions LxWxH	1.22 x 2.75 x 4.53 inches\r\nProduct Benefits	Provides bloating and gas relief",
                            Price = 1000.0,
                            ProductImage = "GasXReliefTablets.jpg",
                            ProductName = "Gas-X Relief Tablets",
                            ProductStatus = "In stock"
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 2,
                            Description = "Brand	Advil\r\nSpecial Feature The medicine in Advil Liqui-Gels(Ibuprofen) is already dissolved in a soft gelatin capsule and works quickly to relieve pain at the site of inflammation.The medicine in Advil Liqui-Gels(Ibuprofen) is already dissolved in a soft gelatin capsule and works quickly to relieve pain at the site of inflammation.\r\nItem Weight 4.64 Ounces\r\nItem Dimensions LxWxH   6 x 5 x 4 inches\r\nProduct Benefits Headache, Menstrual Pain, Joint Pain Relief, Backache, Fever",
                            Price = 2000.0,
                            ProductImage = "AdvilLiquiGels.jpg",
                            ProductName = "Advil Liqui-Gels",
                            ProductStatus = "In stock"
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2,
                            Description = "Brand	Motrin\r\nSpecial Feature Temporarily relieves minor aches and pains\r\nItem Weight 0.18 Grams\r\nItem Dimensions LxWxH   6 x 5 x 4 inches\r\nProduct Benefits Back Pain Relief",
                            Price = 2000.0,
                            ProductImage = "MotrinIB.jpg",
                            ProductName = "Motrin IB",
                            ProductStatus = "In stock"
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 3,
                            Description = "Brand	Amazon Basic Care\r\nSpecial Feature Non Drowsy\r\nItem Dimensions LxWxH   1 x 4.38 x 3.25 inches\r\nProduct Benefits Cold and Flu Control\r\nSpecific Uses For Product Cold",
                            Price = 3000.0,
                            ProductImage = "DaytimeColdandFlu.jpg",
                            ProductName = "Daytime Cold and Flu",
                            ProductStatus = "In stock"
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 3,
                            Description = "Brand	Boiron\r\nSpecial Feature Non Drowsy, Fast Acting\r\nItem Weight 0.04 Ounces\r\nItem Dimensions LxWxH   2 x 2 x 2 inches\r\nProduct Benefits Cold and Flu Control",
                            Price = 3000.0,
                            ProductImage = "BoironOscillococcinum.jpg",
                            ProductName = "Boiron Oscillococcinum",
                            ProductStatus = "In stock"
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 4,
                            Description = "Light Source Type	LED\r\nModel Name  M30 ABS KT2 W\r\nMaterial ABS, Plastic, Metal\r\nColor White\r\nProduct Dimensions  14.57 L x 5.12 W x 15.75H\r\nReal Angle of View  90 Degrees\r\nMagnification Maximum   1200 x\r\nItem Weight 3.7 Pounds\r\n            Brand   AmScope\r\nObjective Lens Description  Achromatic",
                            Price = 4000.0,
                            ProductImage = "AmScope_120X_1200X.jpg",
                            ProductName = "AmScope 120X-1200X 52-pcs",
                            ProductStatus = "In stock"
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 4,
                            Description = "Light Source Type	LED\r\nModel Name  M150C - I 40X - 1000X\r\nMaterial    Glass\r\nColor   Silver, White, Black\r\nProduct Dimensions  10L x 7W x 15H\r\nReal Angle of View  90 Degrees\r\nMagnification Maximum   1000 x\r\nVoltage 110 Volts\r\nBrand   AmScope\r\nObjective Lens Description  Achromatic",
                            Price = 4000.0,
                            ProductImage = "AmScope_M150CI.jpg",
                            ProductName = "AmScope M150C-I 40X-1000X",
                            ProductStatus = "In stock"
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 5,
                            Description = "Brand	Beurer\r\nIncluded Components Cuff\r\nPower Source Battery Powered\r\nUse for Arm\r\nDisplay Type    LCD\r\nSize    Large\r\nAge Range(Description) Adult\r\nItem Weight 12 Ounces\r\nModel Name  BM27\r\nBand Size   16.5 inch",
                            Price = 5000.0,
                            ProductImage = "Beurer_BM27.jpg",
                            ProductName = "Beurer BM27 Upper Arm Blood Pressure Monitor",
                            ProductStatus = "In stock"
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 5,
                            Description = "Brand	angel wish\r\nIncluded Components Home Blood Pressure Monitor x 1; Adjustable Arm Cuff x 1, Users Manual x 1\r\nPower Source    Battery Powered/ Charging Powered\r\nUse for Arm\r\nDisplay Type    LCD\r\nSize    Regular\r\nAge Range(Description) Adult\r\nModel Name  Blood Pressure Monitor\r\nBand Size   12.6 inch\r\nMaterial Feature    Durable",
                            Price = 5000.0,
                            ProductImage = "PortableSmall.jpg",
                            ProductName = "Portable-Small Blood-Pressure Monitors",
                            ProductStatus = "In stock"
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 6,
                            Description = "Brand	Garmin\r\nMaterial    Nylon\r\nColor   Black\r\nCompatible Devices  Smartphones\r\nScreen Size 0.96 Inches\r\nProduct Dimensions  1.18L x 0.47W x 23.62H\r\nItem Weight 51 Grams\r\nBattery Life    8760 Hours\r\nSensor Type Wearable\r\nBattery Description Lithium - Ion",
                            Price = 6000.0,
                            ProductImage = "Garmin.jpg",
                            ProductName = "Garmin 010-13118-00 HRM-Pro Plus",
                            ProductStatus = "In stock"
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 6,
                            Description = "Brand	POLAR\r\nModel Name  Unite\r\nColor   White\r\nScreen Size 1.2 Inches\r\nSpecial Feature Bluetooth\r\nAge Range(Description) Kid\r\nDisplay Type    LED\r\nBand Color  White\r\nBattery Life    4 days\r\nConnectivity Technology Bluetooth",
                            Price = 6000.0,
                            ProductImage = "POLARUnite.jpg",
                            ProductName = "POLAR Unite Waterproof Fitness Watch & H9 Heart Rate Monitor Bundle",
                            ProductStatus = "In stock"
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 7,
                            Description = "Brand   Zacurate\r\nColor   Mystic Black\r\nNumber of Batteries 2 AAA batteries required. (included)\r\nBattery Life    30 Hours\r\nAre Batteries Included  Yes",
                            Price = 7000.0,
                            ProductImage = "Zacurate_500CElite.jpg",
                            ProductName = "Zacurate 500C Elite",
                            ProductStatus = "In stock"
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 7,
                            Description = "Brand	HealthSmart\r\nColor   Red OLED\r\nMeasuring Range 70 % ~99 % ± 2 digits\r\nNumber of Batteries 2 AAA batteries required. (included)\r\nModel Name  HealthSmart Pulse Ox",
                            Price = 7000.0,
                            ProductImage = "HealthSmart.jpg",
                            ProductName = "HealthSmart",
                            ProductStatus = "In stock"
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 8,
                            Description = "Brand	Armedica\r\nShape   Rectangular\r\nProduct Care Instructions   Wipe with Dry Cloth\r\nMaterial    Steel, Welded",
                            Price = 8000.0,
                            ProductImage = "ArmedicaAM_300HILO.jpg",
                            ProductName = "Armedica AM-300 HI-LO",
                            ProductStatus = "In stock"
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 8,
                            Description = "Brand   MedSurface\r\nShape   Rectangular\r\nProduct Care Instructions   Wipe with Dry Cloth",
                            Price = 8000.0,
                            ProductImage = "MedSurfaceMedSurface.jpg",
                            ProductName = "MedSurface Med Surface",
                            ProductStatus = "In stock"
                        });
                });

            modelBuilder.Entity("Project3.Models.Cart", b =>
                {
                    b.HasOne("Project3.Models.Account", "Account")
                        .WithMany("Carts")
                        .HasForeignKey("AccountId");

                    b.HasOne("Project3.Models.Product", "Product")
                        .WithMany("Carts")
                        .HasForeignKey("ProductId");

                    b.Navigation("Account");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Project3.Models.Comment", b =>
                {
                    b.HasOne("Project3.Models.Account", "Account")
                        .WithMany("Comments")
                        .HasForeignKey("AccountId");

                    b.HasOne("Project3.Models.News", "News")
                        .WithMany("Comments")
                        .HasForeignKey("NewsId");

                    b.Navigation("Account");

                    b.Navigation("News");
                });

            modelBuilder.Entity("Project3.Models.OrderDetail", b =>
                {
                    b.HasOne("Project3.Models.Orders", "Orders")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrdersId");

                    b.HasOne("Project3.Models.Product", "Product")
                        .WithMany("OrderDetail")
                        .HasForeignKey("ProductId");

                    b.Navigation("Orders");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Project3.Models.Orders", b =>
                {
                    b.HasOne("Project3.Models.Account", "Account")
                        .WithMany("Orders")
                        .HasForeignKey("AccountId");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Project3.Models.Product", b =>
                {
                    b.HasOne("Project3.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Project3.Models.Account", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Comments");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Project3.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Project3.Models.News", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Project3.Models.Orders", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Project3.Models.Product", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("OrderDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
